import { useEffect, useState } from 'react'
import { BrowserRouter, NavLink, Route, Routes, useLocation } from 'react-router-dom'
import { Activity, AlertTriangle, ArrowRight, ArrowUpRight, Bell, Boxes, Building2, CalendarClock, Check, ChevronDown, ChevronLeft, ChevronRight, CircleHelp, Clock3, Download, Droplets, FileBarChart2, Gauge, HeartPulse, LayoutDashboard, LogOut, Menu, PackageSearch, Search, ShieldAlert, Sparkles, Truck, X } from 'lucide-react'
import { Area, AreaChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { get, getErrorMessage, post } from './services/api'
import NetworkFlow from './components/NetworkFlow.jsx'
import './App.css'

const groups = [
  ['MY HOSPITAL', [['/dashboard', 'Dashboard', LayoutDashboard], ['/inventory', 'Inventory', Boxes], ['/forecasting', 'Forecasting', Activity], ['/shortages', 'Shortage Risk', ShieldAlert], ['/expiry-risk', 'Expiry & Waste', CalendarClock]]],
  ['LOCAL NETWORK', [['/nearby', 'Nearby Hospitals', Building2], ['/redistribution', 'Redistribution', Truck], ['/map', 'Supply Map', Activity]]],
  ['DECISIONS', [['/prioritisation', 'Prioritisation', Gauge], ['/assistant', 'Copilot', Sparkles], ['/reports', 'Reports', FileBarChart2]]],
]
const titles = { '/dashboard': 'Supply intelligence', '/inventory': 'Inventory position', '/forecasting': 'Demand forecasting', '/shortages': 'Shortage risk', '/expiry-risk': 'Expiry & waste', '/redistribution': 'Redistribution queue', '/prioritisation': 'Critical prioritisation', '/hospitals': 'Hospital network', '/supplies': 'Medical supplies', '/assistant': 'MediSupply Copilot', '/reports': 'Reports & exports' }

function useApiData(path, refresh = 0, params = {}) {
  const key = JSON.stringify(params)
  const [state, setState] = useState({ data: null, loading: true, error: '' })
  useEffect(() => {
    let active = true
    setState((previous) => ({ ...previous, loading: true, error: '' }))
    get(path, JSON.parse(key)).then((data) => active && setState({ data, loading: false, error: '' })).catch((error) => active && setState({ data: null, loading: false, error: getErrorMessage(error) }))
    return () => { active = false }
  }, [path, refresh, key])
  return state
}

function LoginScreen({ onLogin }) {
  const [hospitalId, setHospitalId] = useState('H001')
  const [password, setPassword] = useState('demo123')
  const [error, setError] = useState('')
  const [busy, setBusy] = useState(false)
  async function submit(event) {
    event.preventDefault()
    setBusy(true)
    setError('')
    try {
      const session = await post('/auth/login', { hospital_id: hospitalId, password })
      window.localStorage.setItem('stockwatch_session', session.access_token)
      window.localStorage.setItem('stockwatch_user', JSON.stringify(session.user))
      onLogin(session.user)
    } catch (requestError) {
      setError(getErrorMessage(requestError))
    } finally {
      setBusy(false)
    }
  }
  return <main className="login-screen"><div className="login-grid" /><section className="login-panel"><div className="login-brand"><div className="brand-mark"><HeartPulse size={22} /></div><div><strong>StockWatch-RX</strong><small>COIMBATORE SUPPLY INTELLIGENCE</small></div></div><p className="eyebrow">// HOSPITAL ACCESS</p><h1>Know before<br /><span>the shortage.</span></h1><p className="login-description">Sign in to view your hospital's inventory, forecast signals and nearby eligible supply.</p><form onSubmit={submit}><label>Hospital ID<select value={hospitalId} onChange={(event) => setHospitalId(event.target.value)}><option value="H001">H001 · Coimbatore Central Hospital</option><option value="H002">H002 · Coimbatore Emergency Medical Center</option><option value="H003">H003 · Coimbatore Regional Hospital</option></select></label><label>Demo password<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} /></label>{error && <div className="login-error"><AlertTriangle size={15} />{error}</div>}<button className="button button-primary login-button" disabled={busy}>{busy ? 'Signing in...' : 'Enter hospital workspace'}<ArrowRight size={16} /></button></form><div className="login-footer"><span>DEMO MODE</span><span>3 Coimbatore facilities</span></div></section></main>
}

function Shell() {
  const location = useLocation()
  const [authUser, setAuthUser] = useState(() => JSON.parse(window.localStorage.getItem('stockwatch_user') || 'null'))
  const [collapsed, setCollapsed] = useState(false)
  const [mobile, setMobile] = useState(false)
  const [scenario, setScenario] = useState('outbreak')
  const [scenarioLabel, setScenarioLabel] = useState('Outbreak surge')
  const [refresh, setRefresh] = useState(0)
  useEffect(() => { get('/demo/scenario').then((item) => { setScenario(item.key); setScenarioLabel(item.label) }).catch(() => {}) }, [])
  if (!authUser) return <LoginScreen onLogin={setAuthUser} />
  async function selectScenario(event) {
    try { const item = await post('/demo/scenario', { scenario: event.target.value }); setScenario(item.key); setScenarioLabel(item.label); setRefresh((current) => current + 1) }
    catch { event.target.value = scenario }
  }
  return <div className={`app-shell ${collapsed ? 'sidebar-collapsed' : ''}`}>
    <aside className={`sidebar ${mobile ? 'mobile-open' : ''}`}>
      <div className="brand-lockup"><div className="brand-mark"><HeartPulse size={20} /></div><div className="brand-copy"><strong>StockWatch-RX</strong><small>MEDICAL SUPPLY INTELLIGENCE</small></div><button className="mobile-close icon-button" aria-label="Close menu" onClick={() => setMobile(false)}><X size={18} /></button></div>
      <div className="workspace-chip"><div className="workspace-avatar">{authUser.hospital_id}</div><div><strong>Coimbatore</strong><small>{authUser.hospital_name}</small></div></div>
      <nav>{groups.map(([group, links]) => <div className="nav-group" key={group}><div className="nav-group-label">{group}</div>{links.map(([path, label, Icon]) => <NavLink key={path} to={path} onClick={() => setMobile(false)} className={({ isActive }) => `nav-link ${isActive ? 'active' : ''}`} title={collapsed ? label : undefined}><Icon size={18} /><span>{label}</span></NavLink>)}</div>)}</nav>
      <div className="sidebar-bottom"><div className="sidebar-status"><i className="status-dot" /><div><strong>{authUser.hospital_id} · Operational</strong><small>Hospital session active</small></div></div><div className="demo-label">DEMO MODE <i /></div><button className="collapse-button" onClick={() => { window.localStorage.removeItem('stockwatch_session'); window.localStorage.removeItem('stockwatch_user'); setAuthUser(null) }}><LogOut size={15} /><span>Sign out</span></button></div>
    </aside>
    {mobile && <button className="mobile-scrim" aria-label="Close menu" onClick={() => setMobile(false)} />}
    <div className="main-column"><header className="topbar"><button className="mobile-menu icon-button" aria-label="Open menu" onClick={() => setMobile(true)}><Menu size={20} /></button><div className="breadcrumb"><span>STOCKWATCH-RX</span><ChevronRight size={14} /><strong>{titles[location.pathname] || titles['/dashboard']}</strong></div><div className="topbar-actions"><label className="scenario-select"><span>DEMO SCENARIO</span><select value={scenario} onChange={selectScenario} aria-label="Choose demo scenario"><option value="normal">Normal operations</option><option value="outbreak">Outbreak surge</option><option value="critical">Critical shortage</option><option value="expiry">Expiry crisis</option><option value="redistribution">Redistribution opportunity</option></select><ChevronDown size={14} /></label><span className="header-status"><i className="status-dot" />Operational</span><button className="icon-button notification-button" aria-label="Notifications"><Bell size={18} /><i /></button><div className="user-avatar">DR</div></div></header>
      <main className="page-main"><Routes><Route path="/" element={<Dashboard refresh={refresh} scenarioLabel={scenarioLabel} authUser={authUser} />} /><Route path="/dashboard" element={<Dashboard refresh={refresh} scenarioLabel={scenarioLabel} authUser={authUser} />} /><Route path="/inventory" element={<Inventory refresh={refresh} />} /><Route path="/forecasting" element={<Forecast refresh={refresh} />} /><Route path="/shortages" element={<Shortages refresh={refresh} />} /><Route path="/expiry-risk" element={<Expiry refresh={refresh} />} /><Route path="/redistribution" element={<Transfers refresh={refresh} />} /><Route path="/prioritisation" element={<Priorities refresh={refresh} />} /><Route path="/hospitals" element={<Hospitals refresh={refresh} />} /><Route path="/supplies" element={<Supplies refresh={refresh} />} /><Route path="/assistant" element={<Assistant />} /><Route path="/reports" element={<Reports refresh={refresh} />} /><Route path="*" element={<Dashboard refresh={refresh} scenarioLabel={scenarioLabel} authUser={authUser} />} /></Routes><footer className="page-footer"><span>STOCKWATCH-RX · DECISION SUPPORT PROTOTYPE</span><span>Not medical advice · Validate actions with local teams</span></footer></main>
    </div>
  </div>
}

function Heading({ title, description, action }) { return <div className="page-heading"><div><p className="eyebrow">{title === 'Supply intelligence' ? 'NETWORK CONTROL CENTER' : 'OPERATIONS'}</p><h1>{title}</h1><p className="heading-description">{description}</p></div>{action}</div> }
function PanelHeading({ title, eyebrow, action }) { return <div className="panel-heading"><div><span>{eyebrow}</span><h2>{title}</h2></div>{action}</div> }

function DashboardHero({ data, scenarioLabel, authUser }) {
  const lead = data.critical_supplies.find((item) => item.risk_level === 'CRITICAL') || data.critical_supplies[0]
  return <section className="dashboard-hero">
    <div className="hero-copy">
      <div className="hero-overline"><span>// INTELLIGENCE CONTROL CENTER</span><span>01 / SUPPLY NETWORK</span></div>
      <h1>MEDICAL SUPPLY<br /><span>INTELLIGENCE</span></h1>
      <p className="hero-tagline">Know Before the Shortage.</p>
      <p className="hero-description">AI-powered forecasting, risk detection and intelligent redistribution for {authUser?.hospital_name || 'your hospital'}.</p>
      <div className="hero-signals"><span><i className="status-dot" />AI NETWORK ONLINE</span><span>SCENARIO / {scenarioLabel.toUpperCase()}</span><span>LAST UPDATED / {data.updated_at}</span></div>
    </div>
    <aside className="hero-focus"><div className="hero-focus-label"><span>ACTIVE RISK SIGNAL</span><Badge value={lead?.risk_level || 'LOW'} /></div><strong className="hero-focus-days">{lead?.days_until_stockout ?? '--'}<small>DAYS</small></strong><span className="hero-focus-event">SAFETY STOCK BREACH WINDOW</span><span className="hero-focus-name">{lead?.hospital || 'No facility flagged'}</span><span className="hero-focus-supply">{lead?.supply || 'Supply network stable'}</span><div className="hero-focus-footer"><span>{data.kpis.critical_shortages.toString().padStart(2, '0')} CRITICAL SIGNALS</span><span>SIMULATED FORECAST</span></div></aside>
    <div className="hero-baseline" />
  </section>
}

function NearbyPage({ refresh, hospitalId }) {
  const { data, loading, error } = useApiData(`/nearby-hospitals/${hospitalId}`, refresh)
  return <><Heading title="Nearby hospitals" description="Local Coimbatore facilities with eligible surplus for this hospital." /><section className="panel data-panel"><div className="panel-heading"><div><span>LOCAL MATCHING</span><h2>Eligible nearby supply</h2></div><span className="inline-stat"><Activity size={15} />15 km demo radius</span></div>{loading ? <Loading /> : error ? <Error message={error} /> : <div className="nearby-list">{data?.map((item) => <article className="nearby-card" key={item.hospital_id}><div><span className="eyebrow">{item.hospital_id} · {item.distance_km ?? '—'} KM</span><h2>{item.hospital_name}</h2><p>{item.eligible ? `${item.eligible_supplies.length} eligible supply matches` : 'No eligible surplus for current risks'}</p></div><div className="nearby-supplies">{item.eligible_supplies.map((supply) => <span key={supply.supply}>{supply.supply} · {supply.quantity.toLocaleString()} units</span>)}</div></article>)}</div>}</section></>
}

function MapPage({ refresh }) {
  return <><Heading title="Supply map" description="Interactive Coimbatore hospital map with local transfer routes and marker-level risk." /><NetworkFlow refresh={refresh} /></>
}

function Dashboard({ refresh, scenarioLabel, authUser }) {
  const location = useLocation()
  if (location.pathname === '/nearby') return <NearbyPage refresh={refresh} hospitalId={authUser.hospital_id} />
  if (location.pathname === '/map') return <MapPage refresh={refresh} />
  const { data, loading, error } = useApiData('/dashboard/summary', refresh)
  if (loading && !data) return <Loading />
  if (error) return <Error message={error} />
  const metrics = [['Current inventory', data.kpis.current_inventory_units, 'Usable units at this hospital', Boxes, 'green'], ['Critical supplies', data.kpis.critical_supplies_count, 'Require attention', AlertTriangle, 'red'], ['Forecast alerts', data.kpis.forecast_alerts, 'Local demand signals', Activity, 'teal'], ['Expiry risks', data.kpis.expiry_risks, `${data.kpis.stock_at_risk.toLocaleString()} units at risk`, CalendarClock, 'amber'], ['Nearby surplus', data.kpis.nearby_surplus_hospitals, 'Eligible local sources', Truck, 'blue']]
  const totalRisk = Object.values(data.risk_counts).reduce((sum, count) => sum + count, 0)
  return <><DashboardHero data={data} scenarioLabel={scenarioLabel} authUser={authUser} />
    <div className="scenario-banner"><div className="scenario-icon"><Activity size={18} /></div><div><strong>{scenarioLabel}</strong><span>Scenario active · Forecasts and recommendations reflect this selection</span></div><span className="banner-tag">DEMO SIGNAL</span></div>
    <section className="kpi-grid">{metrics.map(([label, value, note, Icon, tone]) => <article className="kpi-card" key={label}><div className={`kpi-icon ${tone}`}><Icon size={18} /></div><div className="kpi-label">{label}</div><div className="kpi-value">{value.toLocaleString()}</div><div className="kpi-note">{note}</div></article>)}</section>
    <div className="dashboard-grid"><section className="panel demand-panel"><PanelHeading title="Demand signal" eyebrow={`${authUser?.hospital_id || 'H001'} · NORMAL SALINE 500ML`} action={<span className="chart-legend"><i className="legend-historical" />History <i className="legend-forecast" />Forecast</span>} /><div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data.demand_chart} margin={{ top: 10, right: 12, left: -18, bottom: 0 }}><defs><linearGradient id="demandFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#167966" stopOpacity={0.2} /><stop offset="95%" stopColor="#167966" stopOpacity={0} /></linearGradient></defs><CartesianGrid vertical={false} stroke="#e9eeec" /><XAxis dataKey="day" tickLine={false} axisLine={false} tick={{ fill: '#84918d', fontSize: 11 }} interval={5} /><YAxis tickLine={false} axisLine={false} tick={{ fill: '#84918d', fontSize: 11 }} /><Tooltip /><Area dataKey="historical" type="monotone" stroke="#167966" strokeWidth={2} fill="url(#demandFill)" connectNulls name="Historical" /><Line dataKey="forecast" type="monotone" stroke="#dc8b37" strokeWidth={2} strokeDasharray="5 4" dot={false} connectNulls name="Forecast" /></AreaChart></ResponsiveContainer></div><div className="chart-footnote"><span><ArrowUpRight size={14} />7-day weighted demand baseline</span><span>Forecast confidence: moderate</span></div></section>
      <section className="panel risk-panel"><PanelHeading title="Network risk mix" eyebrow="SHORTAGE EXPOSURE" action={<NavLink className="text-link" to="/shortages">View all <ArrowRight size={14} /></NavLink>} /><div className="risk-total"><strong>{totalRisk}</strong><span>hospital-supply pairs<br />requiring review</span></div><div className="risk-stacks">{Object.entries(data.risk_counts).map(([risk, count]) => <div className={`risk-stack ${risk.toLowerCase()}`} key={risk}><div className="risk-stack-top"><span><i />{risk}</span><strong>{count}</strong></div><div className="risk-track"><i style={{ width: `${Math.max(4, count / Math.max(1, totalRisk) * 100)}%` }} /></div></div>)}</div><div className="risk-insight"><ShieldAlert size={16} /><span><strong>{data.risk_counts.CRITICAL} critical signals</strong> need near-term action</span></div></section></div>
    <div className="dashboard-grid"><section className="panel table-panel"><PanelHeading title="Recommended transfers" eyebrow="OPTIMISED ACTIONS" action={<NavLink className="text-link" to="/redistribution">Open queue <ArrowRight size={14} /></NavLink>} />{data.transfers.slice(0, 4).map((item) => <TransferRow item={item} key={item.recommendation_id} compact />)}</section><section className="panel table-panel"><PanelHeading title="Expiry watch" eyebrow="WASTE PREVENTION" action={<NavLink className="text-link" to="/expiry-risk">View queue <ArrowRight size={14} /></NavLink>} />{data.expiry_risks.slice(0, 5).map((item) => <div className="expiry-row" key={item.batch_id}><div className="expiry-date"><strong>{item.days_until_expiry}</strong><small>DAYS</small></div><div className="expiry-info"><strong>{item.supply}</strong><span>{item.hospital} · {item.batch_id}</span></div><div className="expiry-units"><strong>{item.expected_waste.toLocaleString()}</strong><small>units exposed</small></div></div>)}</section></div>
    <div className="dashboard-grid"><section className="panel table-panel"><PanelHeading title="Facilities to watch" eyebrow="HOSPITAL SUPPLY HEALTH" action={<NavLink className="text-link" to="/hospitals">All hospitals <ArrowRight size={14} /></NavLink>} />{data.critical_hospitals.map((hospital) => <div className="facility-row" key={hospital.hospital_id}><div className="facility-pin"><Building2 size={15} /></div><div className="facility-info"><strong>{hospital.name}</strong><span>{hospital.city} · {hospital.critical_shortages} critical · {hospital.shortage_count} at risk</span></div><Health score={hospital.supply_health_score} /></div>)}</section><section className="panel priority-callout"><div className="callout-top"><div className="callout-icon"><Gauge size={18} /></div><span>PRIORITY ALLOCATION</span><ArrowUpRight size={16} /></div><h2>Make limited stock count.</h2><p>Urgency, emergency load, patient occupancy, and supply criticality are scored transparently.</p><NavLink to="/prioritisation" className="callout-link">Review allocation ranking <ArrowRight size={15} /></NavLink><div className="callout-metric"><strong>{data.critical_supplies[0]?.priority_score ?? 0}</strong><span>Highest priority score<br />out of 100</span></div></section></div>
    <NetworkFlow refresh={refresh} />
  </>
}

function TransferRow({ item, compact, decide }) { return <div className={`transfer-row ${compact ? 'compact' : ''}`}><div className="transfer-route"><div className="transfer-facility"><i className="route-dot source" /><strong>{item.source_hospital}</strong></div><div className="transfer-arrow"><span>{item.recommended_quantity.toLocaleString()} units</span><ArrowRight size={15} /></div><div className="transfer-facility"><i className="route-dot destination" /><strong>{item.destination_hospital}</strong></div></div><div className="transfer-meta"><div className="transfer-supply"><strong>{item.supply}</strong><span>{item.estimated_transport_hours}h transit · {item.destination_expected_coverage_days}d cover after</span></div><Badge value={item.priority} /><strong className="transfer-score">{item.priority_score}</strong>{decide && <span className="transfer-actions"><button className="button button-approve" onClick={() => decide(item.recommendation_id, 'approve')}><Check size={14} />Approve</button><button className="icon-button" onClick={() => decide(item.recommendation_id, 'reject')} aria-label="Reject"><X size={16} /></button></span>}</div><p className="transfer-reason">{item.reason}</p>{decide && <details className="why-details"><summary>Why this recommendation?<ChevronDown size={15} /></summary><p>Source stock remains above safety stock and its 7-day reserve; destination coverage uses forecast demand.</p></details>}</div> }
function Badge({ value }) { return <span className={`risk-badge ${(value || 'low').toLowerCase()}`}><i />{value || 'LOW'}</span> }
function Health({ score }) { const tone = score < 50 ? 'red' : score < 70 ? 'amber' : 'green'; return <div className="health-meter"><div><i className={tone} style={{ width: `${score}%` }} /></div><strong>{score}</strong></div> }

function Inventory({ refresh }) {
  const { data, loading, error } = useApiData('/inventory', refresh, { page_size: 1000 })
  const hospitals = useApiData('/hospitals', refresh).data || []
  const supplies = useApiData('/supplies', refresh).data || []
  const [search, setSearch] = useState('')
  const [risk, setRisk] = useState('all')
  const [hospitalId, setHospitalId] = useState('all')
  const [supplyId, setSupplyId] = useState('all')
  const [selected, setSelected] = useState(null)
  const rows = (data || []).filter((row) => (!search || `${row.hospital} ${row.supply} ${row.batch_id}`.toLowerCase().includes(search.toLowerCase())) && (risk === 'all' || row.risk_level === risk || row.expiry_risk === risk) && (hospitalId === 'all' || row.hospital_id === hospitalId) && (supplyId === 'all' || row.supply_id === supplyId))
  return <><Heading title="Inventory position" description="Batch-level visibility with projected consumption and expiry exposure." /><section className="panel data-panel"><div className="table-toolbar"><div className="toolbar-search"><Search size={16} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search hospital, supply, or batch" /></div><select value={hospitalId} onChange={(event) => setHospitalId(event.target.value)} className="filter-select"><option value="all">All hospitals</option>{hospitals.map((item) => <option key={item.hospital_id} value={item.hospital_id}>{item.name}</option>)}</select><select value={supplyId} onChange={(event) => setSupplyId(event.target.value)} className="filter-select"><option value="all">All supplies</option>{supplies.map((item) => <option key={item.supply_id} value={item.supply_id}>{item.name}</option>)}</select><select value={risk} onChange={(event) => setRisk(event.target.value)} className="filter-select"><option value="all">All risk levels</option>{['CRITICAL', 'HIGH', 'MEDIUM', 'LOW'].map((item) => <option key={item}>{item}</option>)}</select><span className="filter-count">{rows.length} batches</span></div><Table loading={loading} error={error} rows={rows} click={setSelected} columns={[["Hospital", (r) => <Cell r={r.hospital} sub={r.city} />], ["Supply", (r) => <Cell r={r.supply} sub={r.category} />], ["Batch", (r) => r.batch_id], ["On hand", (r) => r.quantity.toLocaleString()], ["Safety stock", (r) => r.safety_stock.toLocaleString()], ["Daily use", (r) => `${r.daily_demand}/d`], ["Expiry", (r) => `${r.expiry_date} · ${r.days_until_expiry}d`], ["Risk", (r) => <Badge value={r.risk_level} />], ["Waste", (r) => <Badge value={r.expiry_risk} />]]} /></section>{selected && <Drawer title={selected.supply} close={() => setSelected(null)}><Detail label="Hospital" value={selected.hospital} /><Detail label="Batch" value={selected.batch_id} /><Detail label="Quantity" value={selected.quantity.toLocaleString()} /><Detail label="Safety stock" value={selected.safety_stock.toLocaleString()} /><Detail label="Daily forecast" value={`${selected.daily_demand} units`} /><Detail label="Expiry" value={`${selected.expiry_date} (${selected.days_until_expiry} days)`} /></Drawer>}</>
}

function Forecast({ refresh }) {
  const hospitals = useApiData('/hospitals', refresh).data || []
  const supplies = useApiData('/supplies', refresh).data || []
  const [hospital, setHospital] = useState('H001')
  const [supply, setSupply] = useState('MED001')
  const [horizon, setHorizon] = useState('14')
  const { data, loading, error } = useApiData('/forecast', refresh, { hospital_id: hospital, supply_id: supply, horizon_days: Number(horizon) })
  const points = [...(data?.historical_series || []).slice(-20).map((value, index) => ({ label: `-${20 - index}d`, historical: value })), ...(data?.forecast_series || []).map((item) => ({ label: `+${item.day}d`, forecast: item.demand }))]
  return <><Heading title="Demand forecasting" description="Weighted moving average with trend and outbreak adjustments. This prototype makes no claim of medical accuracy." /><section className="panel filter-panel"><Select label="Hospital" value={hospital} change={setHospital} options={hospitals.map((item) => [item.hospital_id, item.name])} /><Select label="Medical supply" value={supply} change={setSupply} options={supplies.map((item) => [item.supply_id, item.name])} /><label className="filter-control"><span>Horizon</span><select value={horizon} onChange={(event) => setHorizon(event.target.value)}><option value="7">7 days</option><option value="14">14 days</option><option value="30">30 days</option><option value="60">60 days</option></select></label></section>{error ? <Error message={error} /> : <><div className="forecast-kpis">{[['Current stock', data?.current_stock?.toLocaleString(), 'units'], ['Average daily demand', data?.average_daily_demand, 'units / day'], ['Forecast demand', data?.forecast_daily_demand, 'units / day'], ['Expected stock-out', `${data?.days_until_stockout ?? '—'} days`, data?.stockout_date]].map(([label, value, note]) => <div className="forecast-metric" key={label}><span>{label}</span><strong>{loading ? '…' : value ?? '—'}</strong><small>{note}</small></div>)}</div><section className="panel forecast-chart-panel"><PanelHeading title={`${data?.supply || 'Supply'} demand curve`} eyebrow={`${hospitals.find((item) => item.hospital_id === hospital)?.name || hospital} · ${horizon} DAY HORIZON`} action={<Badge value={data?.risk_level} />} /><div className="large-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={points}><CartesianGrid vertical={false} stroke="#e8eeeb" /><XAxis dataKey="label" tickLine={false} axisLine={false} interval={4} /><YAxis tickLine={false} axisLine={false} /><Tooltip /><Line dataKey="historical" name="Historical" stroke="#167966" strokeWidth={2} dot={false} connectNulls /><Line dataKey="forecast" name="Forecast" stroke="#dc8b37" strokeWidth={2} strokeDasharray="5 4" dot={false} connectNulls /></LineChart></ResponsiveContainer></div><div className="forecast-explanation"><CircleHelp size={17} /><div><strong>Why this forecast?</strong><p>{data?.explanation}</p><small>7-day weighted moving average · trend adjustment · synthetic outbreak indicator</small></div></div></section></>}</>
}
function Select({ label, value, change, options }) { return <label className="filter-control"><span>{label}</span><select value={value} onChange={(event) => change(event.target.value)}>{options.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label> }

function Shortages({ refresh }) { const { data, loading, error } = useApiData('/shortages', refresh); return <><Heading title="Shortage risk" description="Forecast-ranked supply gaps, ordered by projected stock-out urgency." /><section className="panel data-panel"><Table loading={loading} error={error} rows={data || []} columns={[['Risk', (r) => <Badge value={r.risk_level} />], ['Hospital', (r) => r.hospital], ['Supply', (r) => r.supply], ['On hand', (r) => r.current_stock.toLocaleString()], ['Daily forecast', (r) => `${r.forecast_daily_demand}/d`], ['Stock-out', (r) => <strong className="critical-value">{r.days_until_stockout} days</strong>], ['Probability', (r) => `${Math.round(r.shortage_probability * 100)}%`], ['Driver', (r) => r.outbreak_signal ? 'Outbreak signal' : `Trend ${r.trend_percent}%`]]} /></section></> }

function Expiry({ refresh }) { const { data, loading, error } = useApiData('/expiry-risks', refresh); return <><Heading title="Expiry & waste" description="Expected remaining quantity by batch, projected through expiry." /><section className="panel data-panel"><Table loading={loading} error={error} rows={data || []} columns={[['Risk', (r) => <Badge value={r.risk_level} />], ['Hospital', (r) => r.hospital], ['Supply / batch', (r) => <Cell r={r.supply} sub={r.batch_id} />], ['Quantity', (r) => r.quantity.toLocaleString()], ['Expiry', (r) => `${r.expiry_date} · ${r.days_until_expiry}d`], ['Expected use', (r) => r.expected_usage.toLocaleString()], ['Expected waste', (r) => <strong className="critical-value">{r.expected_waste.toLocaleString()}</strong>], ['Action', (r) => r.recommended_action]]} /></section></> }

function Transfers({ refresh }) {
  const { data, loading, error } = useApiData('/redistribution', refresh)
  const [statuses, setStatuses] = useState({})
  const [toast, setToast] = useState('')
  async function decide(id, action) { try { const result = await post(`/redistribution/${id}/${action}`); setStatuses((current) => ({ ...current, [id]: result.status })); setToast(`Transfer ${result.status}.`); setTimeout(() => setToast(''), 2500) } catch (error) { setToast(getErrorMessage(error)) } }
  return <><Heading title="Redistribution queue" description="Source surplus is protected by safety stock and a 7-day reserve before transfer." />{toast && <div className="toast-message"><Check size={15} />{toast}</div>}{error ? <Error message={error} /> : loading ? <Loading /> : <div className="recommendation-list">{data.map((item) => <article className="panel recommendation-panel" key={item.recommendation_id}><div className="recommendation-top"><div><span className="eyebrow">{item.recommendation_id}</span><h2>{item.supply}</h2></div><Badge value={item.priority} /></div><TransferRow item={item} decide={decide} /><div className="recommendation-details"><Detail label="Source before" value={`${item.source_stock_before.toLocaleString()} units`} /><Detail label="Source after" value={`${item.source_remaining_stock.toLocaleString()} units`} /><Detail label="Destination cover" value={`${item.destination_expected_coverage_days} days`} /><Detail label="Transport" value={`${item.estimated_transport_hours} hours`} /><Detail label="Source expiry" value={item.source_expiry_date} /></div><div className="action-status">Status: <strong>{statuses[item.recommendation_id] || item.status}</strong></div></article>)}</div>}</>
}

function Priorities({ refresh }) { const { data, loading, error } = useApiData('/prioritisation', refresh); return <><Heading title="Critical prioritisation" description="Transparent allocation scoring across emergency demand, patient load, stock-out urgency, alternatives, and criticality." /><section className="score-method"><strong>Priority score weights</strong><div className="weight-chips"><span>Emergency demand <b>35%</b></span><span>Patient load <b>25%</b></span><span>Stock-out urgency <b>20%</b></span><span>Alternative unavailable <b>10%</b></span><span>Supply criticality <b>10%</b></span></div></section><section className="panel data-panel"><Table loading={loading} error={error} rows={data || []} columns={[['Priority', (r) => <Badge value={r.priority} />], ['Hospital', (r) => <Cell r={r.hospital} sub={`${r.days_until_stockout} days cover`} />], ['Supply', (r) => <Cell r={r.supply} sub={`${r.criticality} criticality`} />], ['Score', (r) => <Score value={r.priority_score} />], ['Probability', (r) => `${Math.round(r.shortage_probability * 100)}%`], ['Decision factors', (r) => r.reasons.join(' · ')]]} /></section><p className="method-disclaimer">Scores support operational review; they are not clinical triage.</p></> }

function Hospitals({ refresh }) { const { data, loading, error } = useApiData('/hospitals', refresh); return <><Heading title="Hospital network" description="Facility supply health across the synthetic demo network." /><section className="panel data-panel"><Table loading={loading} error={error} rows={data || []} columns={[['Facility', (r) => <Cell r={r.name} sub={`${r.city}, ${r.state}`} />], ['Beds', (r) => r.bed_capacity], ['Occupancy', (r) => `${Math.round(r.occupancy_rate * 100)}%`], ['Emergency load', (r) => `${Math.round(r.emergency_load * 100)}%`], ['Critical gaps', (r) => r.critical_shortages], ['Expiry flags', (r) => r.expiry_risk_count], ['Supply health', (r) => <Health score={r.supply_health_score} />]]} /></section></> }
function Supplies({ refresh }) { const { data, loading, error } = useApiData('/supplies', refresh); const [search, setSearch] = useState(''); const rows = (data || []).filter((item) => `${item.name} ${item.category}`.toLowerCase().includes(search.toLowerCase())); return <><Heading title="Medical supplies" description="Catalogue-level stock, aggregate demand, and network exposure." /><section className="panel data-panel"><div className="table-toolbar"><div className="toolbar-search"><Search size={16} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search supply or category" /></div></div><Table loading={loading} error={error} rows={rows} columns={[['Supply', (r) => <Cell r={r.name} sub={r.category} />], ['Criticality', (r) => r.criticality], ['Total stock', (r) => r.total_stock.toLocaleString()], ['Daily demand', (r) => `${r.daily_demand.toLocaleString()}/d`], ['14-day forecast', (r) => r.forecast_demand.toLocaleString()], ['Hospitals at risk', (r) => r.shortage_hospitals], ['Expiry batches', (r) => r.expiry_batches], ['Risk', (r) => <Badge value={r.risk_level} />]]} /></section></> }

function Assistant() {
  const [messages, setMessages] = useState([{ role: 'assistant', text: 'I can query current shortage exposure, expiry risk, inventory totals, and recommended transfers. What would you like to know?' }])
  const [question, setQuestion] = useState('')
  const [busy, setBusy] = useState(false)
  const prompts = ['Which supplies are at highest risk at my hospital?', 'Which local batches expire soon?', 'Why should H002 transfer saline to H001?', 'What happens if demand increases by 20%?']
  async function ask(value = question) { const text = value.trim(); if (!text || busy) return; setMessages((items) => [...items, { role: 'user', text }]); setQuestion(''); setBusy(true); try { const result = await post('/assistant/query', { question: text }); setMessages((items) => [...items, { role: 'assistant', text: result.answer, sources: result.sources }]) } catch (error) { setMessages((items) => [...items, { role: 'assistant', text: getErrorMessage(error) }]) } finally { setBusy(false) } }
  return <><Heading title="MediSupply Copilot" description="Natural-language answers grounded in current backend analysis." action={<span className="demo-ai-badge"><Sparkles size={14} />DEMO AI MODE</span>} /><section className="assistant-layout"><div className="panel chat-panel"><div className="chat-header"><div className="chat-avatar"><Sparkles size={18} /></div><div><strong>MediSupply Copilot</strong><span><i className="status-dot" />Connected to demo data</span></div><span className="mode-pill">RULE-BASED</span></div><div className="chat-messages">{messages.map((item, index) => <div className={`chat-message ${item.role}`} key={index}><div className="message-avatar">{item.role === 'assistant' ? <Sparkles size={15} /> : 'DR'}</div><div className="message-body"><p>{item.text}</p>{item.sources && <small>Data sources: {item.sources.map((source) => source.tool.replaceAll('_', ' ')).join(' · ')}</small>}</div></div>)}{busy && <div className="chat-thinking">Checking current supply signals...</div>}</div><form className="chat-compose" onSubmit={(event) => { event.preventDefault(); ask() }}><input value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="Ask about shortages, expiry, or transfers..." /><button disabled={!question.trim() || busy} aria-label="Send"><ArrowRight size={18} /></button></form><div className="chat-disclaimer">Synthetic demo data · Validate decisions with local teams</div></div><aside className="panel prompt-panel"><span className="eyebrow">SUGGESTED QUESTIONS</span><h2>Explore the network</h2>{prompts.map((prompt) => <button className="suggestion-button" key={prompt} onClick={() => ask(prompt)}>{prompt}<ArrowUpRight size={14} /></button>)}</aside></section></>
}

function Reports({ refresh }) {
  const { data: inventory, loading, error } = useApiData('/inventory', refresh, { page_size: 1000 })
  const shortages = useApiData('/shortages', refresh).data || []
  const expiry = useApiData('/expiry-risks', refresh).data || []
  const transfers = useApiData('/redistribution', refresh).data || []
  function exportCsv() { if (!inventory) return; const cols = ['hospital', 'supply', 'batch_id', 'quantity', 'safety_stock', 'daily_demand', 'expiry_date', 'risk_level', 'expiry_risk']; const csv = [cols.join(','), ...inventory.map((row) => cols.map((key) => `"${String(row[key] ?? '').replaceAll('"', '""')}"`).join(','))].join('\r\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); link.download = 'stockwatch-rx-inventory.csv'; link.click(); URL.revokeObjectURL(link.href) }
  const reports = [['Supply health report', 'Inventory batches and network signals', HeartPulse, inventory?.length || 0], ['Shortage report', 'Forecast stock-out risks ranked by urgency', ShieldAlert, shortages.length], ['Expiry risk report', 'Batches with expected waste exposure', CalendarClock, expiry.length], ['Redistribution report', 'Transfers with source safety checks', Truck, transfers.length]]
  return <><Heading title="Reports & exports" description="Operational snapshots generated from the active scenario." action={<button className="button button-primary" onClick={exportCsv} disabled={loading || !inventory}><Download size={15} />Export inventory CSV</button>} />{error && <Error message={error} />}<div className="report-grid">{reports.map(([title, description, Icon, count]) => <article className="panel report-card" key={title}><div className="report-icon"><Icon size={18} /></div><span className="eyebrow">LIVE REPORT</span><h2>{title}</h2><p>{description}</p><div className="report-footer"><span>{count.toLocaleString()} records</span><button className="icon-button" onClick={() => title === 'Supply health report' ? exportCsv() : window.print()} aria-label={`Export ${title}`}><Download size={16} /></button></div></article>)}</div><div className="report-note"><CircleHelp size={16} /><p>Exports contain synthetic demo data. Use the browser print dialog for PDF output.</p></div></>
}

function tableRowKey(row, fallback) { return row.inventory_id || row.recommendation_id || row.batch_id || (row.hospital_id && row.supply_id ? `${row.hospital_id}-${row.supply_id}` : null) || row.supply_id || row.hospital_id || fallback }
function Table({ rows = [], columns, loading, error, click }) { const [page, setPage] = useState(1); const pageSize = 25; const pageCount = Math.max(1, Math.ceil(rows.length / pageSize)); const start = (Math.min(page, pageCount) - 1) * pageSize; const visibleRows = rows.slice(start, start + pageSize); useEffect(() => setPage(1), [rows.length]); if (loading && !rows.length) return <Loading />; if (error) return <Error message={error} />; if (!rows.length) return <div className="empty-state"><PackageSearch size={20} /><strong>No records in this view</strong><span>Try another filter or scenario.</span></div>; return <div className="table-scroll"><table className="data-table"><thead><tr>{columns.map(([label]) => <th key={label}>{label}</th>)}</tr></thead><tbody>{visibleRows.map((row, index) => <tr key={tableRowKey(row, start + index)} className={click ? 'clickable-row' : ''} onClick={click ? () => click(row) : undefined}>{columns.map(([label, render]) => <td key={label}>{render(row, start + index)}</td>)}</tr>)}</tbody></table><div className="table-pagination"><span>Showing {start + 1}–{Math.min(start + pageSize, rows.length)} of {rows.length.toLocaleString()} records</span><div><button disabled={page <= 1} onClick={() => setPage((value) => Math.max(1, value - 1))} aria-label="Previous page"><ChevronLeft size={15} /></button><span>{page} / {pageCount}</span><button disabled={page >= pageCount} onClick={() => setPage((value) => Math.min(pageCount, value + 1))} aria-label="Next page"><ChevronRight size={15} /></button></div></div></div> }
function Cell({ r, sub }) { return <span className="cell-main"><strong>{r}</strong>{sub && <small>{sub}</small>}</span> }
function Detail({ label, value }) { return <div className="detail-line"><span>{label}</span><strong>{value}</strong></div> }
function Score({ value }) { return <span className="score-cell"><strong>{value}</strong><i><b style={{ width: `${value}%` }} /></i></span> }
function Drawer({ title, close, children }) { return <><button className="drawer-scrim" aria-label="Close" onClick={close} /><aside className="detail-drawer"><div className="drawer-header"><h2>{title}</h2><button className="icon-button" onClick={close} aria-label="Close"><X size={18} /></button></div><div className="drawer-content">{children}</div></aside></> }
function Loading() { return <div className="state-panel"><div className="loading-spinner" /><strong>Loading supply intelligence</strong><span>Retrieving current analysis from the API</span></div> }
function Error({ message }) { return <div className="state-panel error-state"><AlertTriangle size={20} /><strong>Unable to load this view</strong><span>{message}</span><small>Confirm the FastAPI service is running at localhost:8000.</small></div> }

export default function App() { return <BrowserRouter><Shell /></BrowserRouter> }
